package com.ja.visitor_reg.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ja.visitor_reg.entity.VisitEventEntity;
import com.ja.visitor_reg.entity.VisitInfoEntity;

import com.ja.visitor_reg.greendao.VisitEventEntityDao;
import com.ja.visitor_reg.greendao.VisitInfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig visitEventEntityDaoConfig;
    private final DaoConfig visitInfoEntityDaoConfig;

    private final VisitEventEntityDao visitEventEntityDao;
    private final VisitInfoEntityDao visitInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        visitEventEntityDaoConfig = daoConfigMap.get(VisitEventEntityDao.class).clone();
        visitEventEntityDaoConfig.initIdentityScope(type);

        visitInfoEntityDaoConfig = daoConfigMap.get(VisitInfoEntityDao.class).clone();
        visitInfoEntityDaoConfig.initIdentityScope(type);

        visitEventEntityDao = new VisitEventEntityDao(visitEventEntityDaoConfig, this);
        visitInfoEntityDao = new VisitInfoEntityDao(visitInfoEntityDaoConfig, this);

        registerDao(VisitEventEntity.class, visitEventEntityDao);
        registerDao(VisitInfoEntity.class, visitInfoEntityDao);
    }
    
    public void clear() {
        visitEventEntityDaoConfig.clearIdentityScope();
        visitInfoEntityDaoConfig.clearIdentityScope();
    }

    public VisitEventEntityDao getVisitEventEntityDao() {
        return visitEventEntityDao;
    }

    public VisitInfoEntityDao getVisitInfoEntityDao() {
        return visitInfoEntityDao;
    }

}
